export const base = {
  fontFamily: '-apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif',
  fontSizeSm: '13px',
  fontSizeMd: '15px',
  fontSizeLg: '17px',
  borderRadius: '5px',
  sizeSm: '16px',
  sizeMd: '24px',
  sizeLg: '32px',
  sizeXl: '44px',
  size2xl: '52px',
  opacitySmall: '0.3',
  opacityMedium: '0.5',
  opacityLarge: '0.85',
  fontWeightNormal: '400',
  fontWeightMedium: '500',
  fontWeightSemiBold: '600',
  fontWeightBold: '700',
  space2xs: '4px',
  spaceXs: '8px',
  spaceSm: '12px',
  spaceMd: '16px',
  spaceLg: '24px',
  spaceXl: '32px',
  space2xl: '40px',
  space3xl: '52px',
  durationFast: '0.15s',
  durationNormal: '0.3s',
  durationSlow: '0.4s',
  transitionDefault: 'ease-in-out',
  lineHeight: '1.4',
  boxShadowStatic: '0px 0px 3px 1px',
  boxShadowActionable: '0 2px 4px 0',
  boxShadowElevated: '0 4px 12px 0',
  boxShadowModal: '0 20px 60px 0'
};
